language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'
  
services:
  - docker

install:
  - composer install
  - sudo ln -s $PWD/bin/terra /usr/local/bin/terra
  - sudo ln -s $PWD/vendor/drush/drush/drush /usr/local/bin/drush
  - ls -la
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

script:
  - terra
  - drush
  - bin/terra app:add drupal http://github.com/terra-ops/example-drupal.git --description='sample app' --host=local.computer -n
  - bin/terra e:a drupal demo demo --enable -n
  - bin/terra status
  
