language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'
  
services:
  - docker

install:
  - composer install
  - ls -la

script:
  - bin/terra
  - bin/terra app:add drupal git@github.com:terra-ops/example-drupal.git --description='sample app' --create-environment --environment-name=demo
  - bin/terra environment:enable drupal demo
  - bin/terra status
  
