language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'
  
services:
  - docker

install:
  - composer install
  - ls -la

script:
  - bin/terra
  - bin/terra app:add drupal8 git@github.com:terra-ops/example-drupal.git 'sample app'
  - bin/terra env:add drupal8 travis --enable
  - bin/terra status
  
