language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'
  
services:
  - docker

install:
  - composer install
  - ls -la

script:
  - bin/terra
  - bin/terra app:add drupal git@github.com:terra-ops/example-drupal.git --description='sample app' --host=local.computer -n
  - terra e:a drupal demo --enable -n
  - bin/terra status
  
